import SwiftUI

struct SettingsView: View {
    @EnvironmentObject private var dependencies: DependencyContainer
    @State private var statusMessage: String?

    var body: some View {
        Form {
            ShortcutSettingsSection()

            Section {
                Text("Replies are generated by your Shortcut. Local plain-text history is stored on this device.")
                    .foregroundStyle(.secondary)
            } header: {
                Text("Privacy")
            }

            Section {
                FontPickerView(selectedFontName: settingsBinding(\.selectedFontName))
            } header: {
                Text("Reply Font")
            }

            Section {
                Button("Clear Local History", role: .destructive) {
                    clearHistory()
                }
            } header: {
                Text("History")
            }

            if let statusMessage {
                Section {
                    Text(statusMessage)
                        .foregroundStyle(.secondary)
                }
            }
        }
    }
}

private extension SettingsView {
    func settingsBinding<Value>(_ keyPath: WritableKeyPath<AppSettings, Value>) -> Binding<Value> {
        Binding {
            dependencies.settings[keyPath: keyPath]
        } set: { newValue in
            dependencies.settings[keyPath: keyPath] = newValue
        }
    }

    func clearHistory() {
        do {
            try dependencies.historyStore.deleteAll()
            statusMessage = "Local history cleared."
        } catch {
            statusMessage = "Could not clear local history."
        }
    }
}
